config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/team', to: 'the_gossip_project#team'
  get '/contact', to: 'the_gossip_project#contact'
  get '/welcome/:name', to: 'the_gossip_project#landing'

  resources :gossips do
    resources :comments, only: [:new, :create, :index, :destroy]
    resources :tags, except: [:destroy]
  end
  resources :cities
  resources :users
  resources :comments, only: [:new, :create, :index, :destroy]
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true

  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: {minimum: 3, maximum: 14, message: "must be between 3 and 14 characters long"}
  validates :content, presence: {message: "can't be blank"}

  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
end

app/models/join_table_pm_recipient.rb
class JoinTablePmRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, presence: true

  belongs_to :sender, class_name: "User"
  has_many :join_table_pm_recipients
  has_many :recipients, class_name: "User", through: :join_table_pm_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  validates :description, presence: true


  belongs_to :city
  has_many :gossips
  
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @city = City.new
  end

  def create
    city = City.create(city_params)
    redirect_to city_path(city.id)
  end

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @city_users = @city.users
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    @city.update(city_params)
    redirect_to cities_path
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_path
  end

  private

  def city_params
    params.require(:city).permit(:name, :slug)
  end

end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def new
#     @comment = Comment.new
#   end

#   def index
#     @comments = Comment.all
#   end

#   def show
#     @comment = Comment.find(params[:id])
#   end

#   def edit
#     @comment = Comment.find(params[:id])
#   end

#   def create
#     @comment = Comment.create(comment_params)
#     redirect_to comment_path(comment.id)
#   end

#   def update
#     @comment = Comment.find(params[:id])
#     @comment.update(comment_params)
#     redirect_to comments_path
#   end

#   def destroy
#     @comment = Comment.find(params[:id])
#     @comment.destroy
#     redirect_to comments_path
#   end
# end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all  
  end 

  def show
    @gossip = Gossip.find(params['id'])
  end 
  
  def new
    @gossip = Gossip.new
  end

  # def create
  #   @gossip = Gossip.new(title: params[:title], content: params[:content], user: User.find(params[:id]))

  #   if @gossip.save
  #     flash[:notice] = 'All good. Your gossip has been saved!'
  #     redirect_to root_path 
  #   else
  #     render '/gossips/new'
  #   end
  # end

  def create
    @gossip = Gossip.create(gossip_params)
    @gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(params[:id])
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: params[:email])
    puts "$" *10
    puts user
    puts "$" *10

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      puts "good redirect"
      redirect_to root_path

    else
      puts "bad redirect"
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to tag_path(tag.id)
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = tag.find(params[:id])
  end

  def edit
    @tag = tag.find(params[:id])
  end

  def update
    @tag = tag.find(params[:id])
    @tag.update
    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.city = City.all.sample

    if @user.save
      puts "user ok"
      log_in(@user)
      redirect_to gossips_path
    else 
      puts "error user"
      puts @user.errors.messages
      redirect_to new_user_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    user_params = params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
 end

  def log_in(user)
   session[:user_id] = user.id
 end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/the_gossip_project_helper.rb
module TheGossipProjectHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/new.html.erb
<h1>City#new</h1>
<p>Find me in app/views/city/new.html.erb</p>

app/views/cities/show.html.erb
  <div class="container text-center">
    <h2 class="p-4">🙊 "<%= @city.name %>" 🙊</h2>
  </div>

  <div class="row justify-content-center">
    <% @city_users.each do |user| %>
      <% user.gossips.each do |gossip| %>
        <div class="card m-3" style="width: 18rem;">
          <div class="list-group">
            <h5 class="card-title"><%= gossip.title %></h5>
            <p class="card-text"><%= gossip.user.first_name %></p>
            <%= link_to "See the full gossip", gossip_path(gossip.id), :class => "btn btn-outline-secondary" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div> 
</div>

app/views/gossips/edit.html.erb
<div class="container text-center">
  <h2 class="text-center p-3">🤫 Edit your gossip 🤫</h2>

<%= form_tag url_for(action: 'update'), method: "post" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <div class="form-group">
    <%= label_tag 'Title', name='Title' %><br/>
    <%= text_field_tag 'title','', size: 50%>
    <br /> <br />
  </div>

  <div class="form-group">
    <%= label_tag 'Content', name='Content' %><br/>
    <%= text_area_tag 'content', nil, size: "50x8" %>
    <br /> <br />
  </div>

  <button type="submit" class="btn btn-outline-secondary">Edit Gossip</button>
  <% end %>
</form>

</div>

app/views/gossips/index.html.erb
<div class="container text-center p-3">
  <% if notice %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
  <% end %>

  <div class="jumbotron pimp text-center">
    <div class="container">
      <h1 class="display-3">Make Gossips great again!</h1>
      <p>A life of gossips.</p>
      <p><a class="btn btn-primary btn-lg" href=<%= new_gossip_path %> role="button">Create a gossip</a></p>

    </div>
  </div>

  <h2 class="text-center p-3">🔽 Welcome to the best Gossip website EVER 🔽</h2>
  <div class="row justify-content-center">
    <% @gossips.each_with_index do |gossip, i| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="list-group">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-text"><%= gossip.user.first_name %></p>
          <%= link_to "See the full gossip", gossip_path(gossip.id), :class => "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<div class="container text-center">
  <h2 class="text-center p-3">🤫 Create your gossip 🤫</h2>

  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <% if @gossip.errors.any? %>
      <% @gossip.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= label_tag 'Title', name='Title' %><br/>
      <%= text_field_tag 'title','', size: 50%>
      <br /> <br />
    </div>

    <div class="form-group">
      <%= label_tag 'Content', name='Content' %><br/>
      <%= text_area_tag 'content', nil, size: "50x8" %>
      <br /> <br />
    </div>

    <button type="submit" class="btn btn-outline-secondary">Create Gossip</button>
    <% end %>
  </form>

</div>

app/views/gossips/show.html.erb
<div class="container text-center">

  <h2 class="p-4">🙊 "<%= @gossip.title %>" 🙊</h2>

  <p><b>Title:</b> <%= @gossip.title %></p>
  <p><b>Content:</b> <%= @gossip.content %></p>
  <p class="p-3"><b>Author:</b> <%= @gossip.user.first_name %></p>
  <p><b>City:</b> <%= @gossip.user.city.name %></p>
  <p><b>Creation date:</b> <%= @gossip.created_at %></p>
  
  <%= link_to "User profile", user_path(Gossip.all.find_by(id: params['id'])), :class => "btn btn-outline-primary m-4" %>
  <%= link_to "City page", city_path(@gossip.user.city.id), :class => "btn btn-outline-secondary" %>
  <%= link_to "Edit gossip", edit_gossip_path(:id), :class => "btn btn-outline-warning" %>
  <%= link_to "Delete gossip", gossips_path, :class => "btn btn-outline-danger" %>

  <h1 class="p-3"> </h1>
  <div class="form-group">
    <button type="submit">Comment here</button>
  </div>

</div>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<h2 class="text-center p-3"> 🤹‍♀️ Users 🤹‍♀️ </h2>
  <div class="row justify-content-center">
    <% @users.each_with_index do |user, i| %>
      <div class="card m-3" style="width: 18rem;">
        <div class="list-group">
          <h5 class="card-title"><%= user.first_name %></h5>
          <p class="card-text"><%= user.last_name %></p>
          <%= link_to "User profile", user_path(Gossip.all.find_by(id: params['id'])), :class => "btn btn-outline-primary m-4" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/new.html.erb
<div class="container text-center">
  <h2 class="text-center p-3">🚴‍♂️ Create your user 🚴‍♂️</h2>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
          <%= message %>
        </div>
      <% end %>
    <% end %>

  <%= form_for @user do |f| %>

    <div class="form-group">
      <label>First Name</label>
      <%= f.text_field :first_name, class:'form-control' %>
    </div>    
    <div class="form-group">
      <label>Last Name</label>
      <%= f.text_field :last_name, class:'form-control' %>
    </div>
    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, class:'form-control' %>
    </div>
    <div class="form-group">
      <label>Email</label>
      <%= f.text_field :email, class:'form-control' %>
    </div>
    <div class="form-group">
      <label>Age</label>
      <%= f.text_field :age, class:'form-control' %>
    </div>
    <div class="form-group">
      <label>Password</label>
      <%= f.password_field :password, class:'form-control' %>
    </div>
    <button type="submit" class="btn btn-outline-success">Create User</button>
    <% end %>
  </form>

</div>

app/views/users/show.html.erb
<div class="container text-center">
  
  <h2 class="p-4">✒️ <%= @user.first_name %> <%= @user.last_name %> 🖋️</h2>
  <%
=begin%>
 <p><b>Name:</b> <%= @user.name %></p> 
<%
=end%>
  <p class="p-3"><b>Description:</b> <%= @user.description %></p>
  <p><b>Email:</b> <%= @user.email %></p>
  <p><b>Age:</b> <%= @user.age %></p>
  <p><b>City:</b> <%= @user.city.name %></p>
  <%
=begin%>
 <img src="http://i.stack.imgur.com/SBv4T.gif" alt="this slowpoke moves"  width=300/> 
<%
=end%>
  <%= link_to "See the city page", city_path(@user.city.id), :class => "btn btn-outline-secondary" %>

</div>