config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/team', to: 'the_gossip_project#team'
  get '/contact', to: 'the_gossip_project#contact'
  get '/welcome/:name', to: 'the_gossip_project#landing'

  resources :gossips do
    resources :comments, only: [:new, :create, :index, :destroy]
    resources :tags, except: [:destroy]
  end
  resources :cities
  resources :users
  resources :comments, only: [:new, :create, :index, :destroy]
  resources :tags
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :zip_code, presence: true

  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: {minimum: 3, maximum: 14, message: "must be between 3 and 14 characters long"}
  validates :content, presence: {message: "can't be blank"}

  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
end

app/models/join_table_pm_recipient.rb
class JoinTablePmRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, presence: true

  belongs_to :sender, class_name: "User"
  has_many :join_table_pm_recipients
  has_many :recipients, class_name: "User", through: :join_table_pm_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  validates :description, presence: true


  belongs_to :city
  has_many :gossips
  
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  has_secure_password
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @city = City.new
  end

  def create
    city = City.create(city_params)
    redirect_to city_path(city.id)
  end

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @city_users = @city.users
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    @city.update(city_params)
    redirect_to cities_path
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to cities_path
  end

  private

  def city_params
    params.require(:city).permit(:name, :slug)
  end

end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def new
#     @comment = Comment.new
#   end

#   def index
#     @comments = Comment.all
#   end

#   def show
#     @comment = Comment.find(params[:id])
#   end

#   def edit
#     @comment = Comment.find(params[:id])
#   end

#   def create
#     @comment = Comment.create(comment_params)
#     redirect_to comment_path(comment.id)
#   end

#   def update
#     @comment = Comment.find(params[:id])
#     @comment.update(comment_params)
#     redirect_to comments_path
#   end

#   def destroy
#     @comment = Comment.find(params[:id])
#     @comment.destroy
#     redirect_to comments_path
#   end
# end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all  
  end 

  def show
    @gossip = Gossip.find(params['id'])
  end 
  
  def new
    @gossip = Gossip.new
  end

  # def create
  #   @gossip = Gossip.new(title: params[:title], content: params[:content], user: User.find(params[:id]))

  #   if @gossip.save
  #     flash[:notice] = 'All good. Your gossip has been saved!'
  #     redirect_to root_path 
  #   else
  #     render '/gossips/new'
  #   end
  # end

  def create
    @gossip = Gossip.create(gossip_params)
    @gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(params[:id])
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    redirect_to tag_path(tag.id)
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = tag.find(params[:id])
  end

  def edit
    @tag = tag.find(params[:id])
  end

  def update
    @tag = tag.find(params[:id])
    @tag.update
    redirect_to tags_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.city = City.all.sample

    if @user.save
      puts "user ok"
      log_in(@user)
      redirect_to gossips_path
    else 
      puts "error user"
      puts @user.errors.messages
      redirect_to new_user_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    user_params = params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
 end

  def log_in(user)
   session[:user_id] = user.id
 end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGossipProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Team", team_path, :class => "nav-item nav-link" %>
        </li>  
        <li class="nav-item">
          <%= link_to "Contact", contact_path, :class => "nav-item nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create a gossip", new_gossip_path, :class => "nav-item nav-link" %>
        </li>
      </ul>
        
      <ul class="nav-bar ml-auto">
          <% if current_user == nil %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown button
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Log in", new_session_path, :class => "nav-item nav-link" %>
            <%= link_to "Sign up", new_user_path, :class => "nav-item nav-link" %>
          <% else %>
            <%= link_to "Log out", session_path(session.id), :class => "btn btn-outline-danger", :method => :DELETE, :data => {:confirm => "Are you sure ?"} %>
          <% end %> 
          </div>
        </div>
      </ul>
    </div>
  </nav>

  <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>